# Generated by Django 4.0.1 on 2023-01-11 20:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0002_professor_student_timetable_proposal_meeting_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='user_type',
            field=models.CharField(choices=[('Student', 'Student'), ('Professor', 'Professor')], default='Student', max_length=10),
        ),
    ]
