# Generated by Django 4.0.1 on 2023-01-12 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0003_alter_user_user_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='status',
            name='submitted',
            field=models.BooleanField(default=True),
        ),
    ]
