# Generated by Django 4.0.1 on 2023-01-12 20:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0007_files_proposal_alter_files_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='meeting',
            name='rejected',
            field=models.BooleanField(default=False),
        ),
    ]
