# Generated by Django 4.0.1 on 2023-01-13 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0009_alter_timetable_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='timetable',
            name='accepted',
            field=models.BooleanField(default=False),
        ),
    ]
