# Generated by Django 4.0.1 on 2023-01-21 20:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0015_rename_id_accepted_accepted_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='accepted',
            old_name='accepted_id',
            new_name='id',
        ),
    ]
