# Generated by Django 4.0.1 on 2023-01-23 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0016_rename_accepted_id_accepted_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='user_type',
            field=models.CharField(choices=[('New', 'New'), ('Student', 'Student'), ('Professor', 'Professor')], default='New', max_length=10),
        ),
    ]
