# Generated by Django 4.0.1 on 2023-01-26 16:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0017_alter_user_user_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='status',
            name='files',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='project.files'),
        ),
    ]
