# Generated by Django 4.0.1 on 2023-01-26 16:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0018_status_files'),
    ]

    operations = [
        migrations.AlterField(
            model_name='status',
            name='files',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='project.files'),
        ),
    ]
