# Generated by Django 4.0.1 on 2023-02-02 12:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0019_alter_status_files'),
    ]

    operations = [
        migrations.AlterField(
            model_name='status',
            name='files',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='project.files'),
        ),
    ]
