# Generated by Django 4.0.1 on 2023-02-06 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0021_remove_demonstration_timetable_demonstration_time_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='demonstration',
            name='date',
            field=models.DateField(default='2023-03-01'),
        ),
    ]
