# Generated by Django 4.0.1 on 2023-02-08 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0023_remove_timetable_venue_alter_timetable_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='year',
            field=models.IntegerField(default=3),
        ),
    ]
