# Generated by Django 4.0.1 on 2023-02-08 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0025_alter_files_documentation_alter_files_srs'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='course',
            field=models.CharField(default='CASE', max_length=10),
        ),
    ]
