# Generated by Django 4.0.1 on 2023-02-08 21:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0026_student_course'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='user_type',
            field=models.CharField(choices=[('New', 'New'), ('Student', 'Student'), ('Professor', 'Professor'), ('New_Professor', 'New_Professor')], default='New', max_length=15),
        ),
    ]
