# Generated by Django 4.0.1 on 2023-02-12 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0027_alter_user_user_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timetable',
            name='time',
            field=models.CharField(choices=[('09:00', '09:00'), ('10:00', '10:00'), ('11:00', '11:00'), ('12:00', '12:00'), ('14:00', '14:00'), ('15:00', '15:00'), ('16:00', '16:00'), ('17:00', '17:00')], default='09:00', max_length=20),
        ),
    ]
