# Generated by Django 4.0.1 on 2023-02-15 13:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0028_alter_timetable_time'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Demonstration',
            new_name='DemonstrationItem',
        ),
    ]
