# Generated by Django 4.0.1 on 2023-02-15 14:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0029_rename_demonstration_demonstrationitem'),
    ]

    operations = [
        migrations.CreateModel(
            name='Demonstration',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('start_date', models.DateField()),
                ('number_of_assesors', models.IntegerField(default=2)),
            ],
        ),
        migrations.RemoveField(
            model_name='demonstrationitem',
            name='professor',
        ),
        migrations.AlterField(
            model_name='demonstrationitem',
            name='date',
            field=models.DateField(),
        ),
        migrations.CreateModel(
            name='Venues',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('venue', models.CharField(max_length=50)),
                ('places', models.IntegerField()),
                ('demo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='project.demonstration')),
            ],
        ),
        migrations.CreateModel(
            name='Assessors',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('assesor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='project.professor')),
                ('demoItem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='project.demonstrationitem')),
            ],
        ),
        migrations.AddField(
            model_name='demonstrationitem',
            name='demo',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='project.demonstration'),
        ),
        migrations.AlterField(
            model_name='demonstrationitem',
            name='venue',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='project.venues'),
        ),
    ]
