# Generated by Django 4.0.1 on 2023-02-15 14:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0030_demonstration_remove_demonstrationitem_professor_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='demonstrationitem',
            name='venue',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='project.venues'),
        ),
    ]
