# Generated by Django 4.0.1 on 2023-02-15 15:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0031_alter_demonstrationitem_venue'),
    ]

    operations = [
        migrations.RenameField(
            model_name='demonstration',
            old_name='number_of_assesors',
            new_name='number_of_assessors',
        ),
    ]
