# Generated by Django 4.0.1 on 2023-02-18 19:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0033_alter_venues_demo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accepted',
            name='proposal',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='project.proposal'),
        ),
    ]
