# Generated by Django 4.0.1 on 2023-02-21 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0037_alter_professor_email_alter_student_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='timetable',
            name='accepted',
        ),
        migrations.AddField(
            model_name='accepted',
            name='default',
            field=models.BooleanField(default=False),
        ),
    ]
