# Generated by Django 4.0.1 on 2023-02-22 23:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0038_remove_timetable_accepted_accepted_default'),
    ]

    operations = [
        migrations.AlterField(
            model_name='professor',
            name='email',
            field=models.EmailField(max_length=50),
        ),
        migrations.AlterField(
            model_name='student',
            name='email',
            field=models.EmailField(max_length=50),
        ),
    ]
