# Generated by Django 4.0.1 on 2023-02-23 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0039_alter_professor_email_alter_student_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='marking',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
